# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    sudo apt-get update
    sudo apt-get install --yes --no-install-recommends meson clang-format-8 clang-tidy-8 cppcheck
  displayName: 'Install required software'

- script: |
    meson setup build
    cd build
    ninja
  displayName: 'Build the project'

- script: |
    ninja format
  displayName: 'Do clang-format'

- script: |
    ninja tidy
  displayName: 'Do clang-tidy'

- script: |
    ninja cppcheck
  displayName: 'Do cppcheck'

- script: |
    ninja test
  displayName: 'Do tests'