# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7' 

- script: |
    wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
    sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main"
    sudo apt-get update
    sudo apt-get install --yes --no-install-recommends clang-format-8 clang-tidy-8 cppcheck python3-setuptools
    sudo pip3 install ninja meson
  displayName: 'Install required software'

- script: |
    meson setup build
    cd build
    ninja
  displayName: 'Build the project'

- script: cd build && ninja format
  displayName: 'Do clang-format'

- script: cd build && ninja tidy
  displayName: 'Do clang-tidy'

- script: cd build && ninja cppcheck
  displayName: 'Do cppcheck'

- script: cd build && ninja test
  displayName: 'Do tests'
